// <auto-generated />
using System;
using ContactApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactApp.API.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20211221111752_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactApp.API.Data.Model.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firm")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "e96bb9b2-0d70-4c8f-8344-20872e24010c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 919, DateTimeKind.Utc).AddTicks(5263),
                            Firm = "Rise Consulting",
                            FirstName = "Hasan",
                            IsDeleted = false,
                            LastName = "Erdal",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 919, DateTimeKind.Utc).AddTicks(5552)
                        },
                        new
                        {
                            Id = "06aa8dd6-12b2-45f0-9087-222889639d1c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 919, DateTimeKind.Utc).AddTicks(6037),
                            Firm = "No Firm",
                            FirstName = "Mehmet",
                            IsDeleted = false,
                            LastName = "Erdal",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 919, DateTimeKind.Utc).AddTicks(6039)
                        },
                        new
                        {
                            Id = "13539989-0439-4698-b694-ad6a8e65d5ab",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 919, DateTimeKind.Utc).AddTicks(6041),
                            Firm = "No Firm",
                            FirstName = "Mustafa",
                            IsDeleted = false,
                            LastName = "Erdal",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 919, DateTimeKind.Utc).AddTicks(6042)
                        });
                });

            modelBuilder.Entity("ContactApp.API.Data.Model.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId", "Key")
                        .IsUnique()
                        .HasFilter("[ContactId] IS NOT NULL");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactId = "e96bb9b2-0d70-4c8f-8344-20872e24010c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(260),
                            IsDeleted = false,
                            Key = "Telefon Numarası",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(269),
                            Value = "+90 537 035 2059"
                        },
                        new
                        {
                            Id = 2,
                            ContactId = "e96bb9b2-0d70-4c8f-8344-20872e24010c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(273),
                            IsDeleted = false,
                            Key = "E-Mail Adresi",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(273),
                            Value = "hasaerda@hotmail.com"
                        },
                        new
                        {
                            Id = 3,
                            ContactId = "e96bb9b2-0d70-4c8f-8344-20872e24010c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(275),
                            IsDeleted = false,
                            Key = "Konum",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(276),
                            Value = "Şahinbey/Gaziantep"
                        },
                        new
                        {
                            Id = 4,
                            ContactId = "06aa8dd6-12b2-45f0-9087-222889639d1c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(277),
                            IsDeleted = false,
                            Key = "Telefon Numarası",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(278),
                            Value = "+90 537 035 2059"
                        },
                        new
                        {
                            Id = 5,
                            ContactId = "06aa8dd6-12b2-45f0-9087-222889639d1c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(279),
                            IsDeleted = false,
                            Key = "E-Mail Adresi",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(280),
                            Value = "hasaerda@hotmail.com"
                        },
                        new
                        {
                            Id = 6,
                            ContactId = "06aa8dd6-12b2-45f0-9087-222889639d1c",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(281),
                            IsDeleted = false,
                            Key = "Konum",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(282),
                            Value = "Şahinbey/Gaziantep"
                        },
                        new
                        {
                            Id = 7,
                            ContactId = "13539989-0439-4698-b694-ad6a8e65d5ab",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(283),
                            IsDeleted = false,
                            Key = "Telefon Numarası",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(284),
                            Value = "+90 537 035 2059"
                        },
                        new
                        {
                            Id = 8,
                            ContactId = "13539989-0439-4698-b694-ad6a8e65d5ab",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(285),
                            IsDeleted = false,
                            Key = "E-Mail Adresi",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(286),
                            Value = "hasaerda@hotmail.com"
                        },
                        new
                        {
                            Id = 9,
                            ContactId = "13539989-0439-4698-b694-ad6a8e65d5ab",
                            CreatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(287),
                            IsDeleted = false,
                            Key = "Konum",
                            UpdatedAt = new DateTime(2021, 12, 21, 11, 17, 51, 921, DateTimeKind.Utc).AddTicks(287),
                            Value = "Şehitkamil/Gaziantep"
                        });
                });

            modelBuilder.Entity("ContactApp.API.Data.Model.ContactInfo", b =>
                {
                    b.HasOne("ContactApp.API.Data.Model.Contact", "Contact")
                        .WithMany("ContactInfos")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ContactApp.API.Data.Model.Contact", b =>
                {
                    b.Navigation("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
